/* SEN Soundscapes — Volume 1 (catalog version 1.0.1): the 43 scores from the
   "SEN-Soundscapes-Volume-1.spp" pack. Titles, moods and tags are the pack's
   AI-proposed listening metadata (not human-approved); durations are measured.
   Audio is served from media.seihouse.org, which sends CORS headers, so every
   track also plays on the reader mixer's Web Audio route. */

export interface SenSoundscape {
    /** Stable pack id, e.g. SEN_VOL1_ADVENTURE_1. */
    id: string
    /** Source folder in the pack. */
    category: SenSoundscapeCategory
    /** Track number within its category. */
    number: number
    /** AI-proposed display title. */
    title: string
    mood: string
    tags: readonly string[]
    durationSeconds: number
    url: string
}

export type SenSoundscapeCategory = "Adventure" | "Ambient" | "Emotions" | "Fighting" | "War"

export const SEN_SOUNDSCAPE_CATEGORIES: readonly SenSoundscapeCategory[] = [
    "Adventure",
    "Ambient",
    "Emotions",
    "Fighting",
    "War",
]

export const SEN_SOUNDSCAPES_VOLUME_1: readonly SenSoundscape[] = [
    {
        id: "SEN_VOL1_ADVENTURE_1",
        category: "Adventure",
        number: 1,
        title: "Grand Orchestral Fanfare",
        mood: "triumph",
        tags: ["adventure", "triumph", "orchestral", "heroic", "epic"],
        durationSeconds: 154,
        url: "https://media.seihouse.org/SEN/AUDIO/SOUNDSCAPE/Volumn%201/ADVENTURE/1.%20ADVENTURE.mp3",
    },
    {
        id: "SEN_VOL1_ADVENTURE_2",
        category: "Adventure",
        number: 2,
        title: "Ancient Flute Melancholy",
        mood: "serenity",
        tags: ["traditional", "folk", "meditative", "peaceful", "contemplative"],
        durationSeconds: 153,
        url: "https://media.seihouse.org/SEN/AUDIO/SOUNDSCAPE/Volumn%201/ADVENTURE/2.%20ADVENTURE.mp3",
    },
    {
        id: "SEN_VOL1_ADVENTURE_3",
        category: "Adventure",
        number: 3,
        title: "Mystical Fanfare and Melodic Journey",
        mood: "mystical",
        tags: [
            "adventure",
            "fantasy",
            "cinematic",
            "traditional",
            "ornate",
            "soaring",
            "majestic",
            "ethereal",
        ],
        durationSeconds: 175,
        url: "https://media.seihouse.org/SEN/AUDIO/SOUNDSCAPE/Volumn%201/ADVENTURE/3.%20ADVENTURE.wav",
    },
    {
        id: "SEN_VOL1_ADVENTURE_4",
        category: "Adventure",
        number: 4,
        title: "Mystical Overture and Epic Journey",
        mood: "adventure",
        tags: ["adventure", "orchestral", "cinematic", "fantasy", "battle", "epic"],
        durationSeconds: 160,
        url: "https://media.seihouse.org/SEN/AUDIO/SOUNDSCAPE/Volumn%201/ADVENTURE/4.%20ADVENTURE.wav",
    },
    {
        id: "SEN_VOL1_ADVENTURE_5",
        category: "Adventure",
        number: 5,
        title: "Traditional Eastern Flute Lament",
        mood: "sad",
        tags: ["mystical", "tragedy", "ambient", "serenity", "historical", "meditative"],
        durationSeconds: 146,
        url: "https://media.seihouse.org/SEN/AUDIO/SOUNDSCAPE/Volumn%201/ADVENTURE/5.%20ADVENTURE.mp3",
    },
    {
        id: "SEN_VOL1_ADVENTURE_6",
        category: "Adventure",
        number: 6,
        title: "Ancient Flute Melodies",
        mood: "mystical",
        tags: ["adventure", "mystical", "ambient", "travel", "serenity"],
        durationSeconds: 164,
        url: "https://media.seihouse.org/SEN/AUDIO/SOUNDSCAPE/Volumn%201/ADVENTURE/6.%20ADVENTURE.wav",
    },
    {
        id: "SEN_VOL1_ADVENTURE_7",
        category: "Adventure",
        number: 7,
        title: "Traditional Eastern Mystic Soundscape",
        mood: "mystical",
        tags: [
            "ambient",
            "adventure",
            "mystical",
            "serenity",
            "mystery",
            "tragedy",
            "traditional",
            "cinematic",
        ],
        durationSeconds: 152,
        url: "https://media.seihouse.org/SEN/AUDIO/SOUNDSCAPE/Volumn%201/ADVENTURE/7.%20ADVENTURE.mp3",
    },
    {
        id: "SEN_VOL1_ADVENTURE_8",
        category: "Adventure",
        number: 8,
        title: "Epic Fantasy Battle Theme",
        mood: "excitement",
        tags: ["orchestral", "epic", "cinematic", "action", "heroic", "fantasy", "fast-paced"],
        durationSeconds: 182,
        url: "https://media.seihouse.org/SEN/AUDIO/SOUNDSCAPE/Volumn%201/ADVENTURE/8.%20ADVENTURE.mp3",
    },
    {
        id: "SEN_VOL1_ADVENTURE_9",
        category: "Adventure",
        number: 9,
        title: "Mystical Vocal Chant and Orchestral Ascent",
        mood: "mystical",
        tags: ["cinematic", "atmospheric", "orchestral", "ethereal", "epic"],
        durationSeconds: 179,
        url: "https://media.seihouse.org/SEN/AUDIO/SOUNDSCAPE/Volumn%201/ADVENTURE/9%20ADVENTURE.mp3",
    },
    {
        id: "SEN_VOL1_ADVENTURE_10",
        category: "Adventure",
        number: 10,
        title: "Traditional Eastern Instrumental Medley",
        mood: "serenity",
        tags: [
            "ambient",
            "meditative",
            "serenity",
            "mystical",
            "travel",
            "traditional",
            "acoustic",
        ],
        durationSeconds: 178,
        url: "https://media.seihouse.org/SEN/AUDIO/SOUNDSCAPE/Volumn%201/ADVENTURE/10%20ADVENTURE.mp3",
    },
    {
        id: "SEN_VOL1_AMBIENT_1",
        category: "Ambient",
        number: 1,
        title: "Ancient Journey",
        mood: "adventure",
        tags: ["adventure", "travel", "mystical", "cinematic", "traditional", "orchestral"],
        durationSeconds: 162,
        url: "https://media.seihouse.org/SEN/AUDIO/SOUNDSCAPE/Volumn%201/AMBIENT/1.%20AMBEINT.wav",
    },
    {
        id: "SEN_VOL1_AMBIENT_2",
        category: "Ambient",
        number: 2,
        title: "Melancholic Piano Melody",
        mood: "sad",
        tags: ["sad", "serenity", "mystery", "melancholy", "reflective", "solitary"],
        durationSeconds: 90,
        url: "https://media.seihouse.org/SEN/AUDIO/SOUNDSCAPE/Volumn%201/AMBIENT/2.%20AMBEINT.wav",
    },
    {
        id: "SEN_VOL1_AMBIENT_3",
        category: "Ambient",
        number: 3,
        title: "Ethereal Mystical Soundscape",
        mood: "mystical",
        tags: [
            "mystical",
            "ambient",
            "serenity",
            "suspenseful",
            "ethereal",
            "cinematic",
            "orchestral",
        ],
        durationSeconds: 148,
        url: "https://media.seihouse.org/SEN/AUDIO/SOUNDSCAPE/Volumn%201/AMBIENT/3.%20AMBEINT.mp3",
    },
    {
        id: "SEN_VOL1_AMBIENT_4",
        category: "Ambient",
        number: 4,
        title: "Ambient Soundscape with Vocalization",
        mood: "mystical",
        tags: ["ambient", "serenity", "mystery", "mystical", "atmospheric", "ethereal"],
        durationSeconds: 172,
        url: "https://media.seihouse.org/SEN/AUDIO/SOUNDSCAPE/Volumn%201/AMBIENT/4.%20AMBEINT.mp3",
    },
    {
        id: "SEN_VOL1_AMBIENT_5",
        category: "Ambient",
        number: 5,
        title: "Ancient Temple Serenade",
        mood: "mystical",
        tags: [
            "adventure",
            "ambient",
            "mystical",
            "serenity",
            "tragedy",
            "cinematic",
            "historical",
            "folk",
        ],
        durationSeconds: 157,
        url: "https://media.seihouse.org/SEN/AUDIO/SOUNDSCAPE/Volumn%201/AMBIENT/5.%20AMBEINT.mp3",
    },
    {
        id: "SEN_VOL1_AMBIENT_6",
        category: "Ambient",
        number: 6,
        title: "Ancient Journey",
        mood: "mystical",
        tags: [
            "adventure",
            "ambient",
            "travel",
            "serenity",
            "mystery",
            "mystical",
            "cinematic",
            "orchestral",
        ],
        durationSeconds: 159,
        url: "https://media.seihouse.org/SEN/AUDIO/SOUNDSCAPE/Volumn%201/AMBIENT/6.%20AMBEINT.wav",
    },
    {
        id: "SEN_VOL1_AMBIENT_7",
        category: "Ambient",
        number: 7,
        title: "Solitary Lute Reflection",
        mood: "melancholic",
        tags: ["ambient", "meditation", "solitary", "traditional", "acoustic"],
        durationSeconds: 173,
        url: "https://media.seihouse.org/SEN/AUDIO/SOUNDSCAPE/Volumn%201/AMBIENT/7.%20AMBEINT.mp3",
    },
    {
        id: "SEN_VOL1_AMBIENT_8",
        category: "Ambient",
        number: 8,
        title: "Ancient Melancholy Flute",
        mood: "sad",
        tags: ["ambient", "sad", "tragedy", "mystical", "historical", "cinematic"],
        durationSeconds: 171,
        url: "https://media.seihouse.org/SEN/AUDIO/SOUNDSCAPE/Volumn%201/AMBIENT/8.%20AMBEINT.mp3",
    },
    {
        id: "SEN_VOL1_AMBIENT_9",
        category: "Ambient",
        number: 9,
        title: "Melancholy Zither Melody",
        mood: "melancholy",
        tags: ["ambient", "mystical", "acoustic", "solitary", "meditative"],
        durationSeconds: 181,
        url: "https://media.seihouse.org/SEN/AUDIO/SOUNDSCAPE/Volumn%201/AMBIENT/9.%20AMBEINT.mp3",
    },
    {
        id: "SEN_VOL1_AMBIENT_10",
        category: "Ambient",
        number: 10,
        title: "Ancient Echoes",
        mood: "serenity",
        tags: [
            "ambient",
            "serenity",
            "mystery",
            "mystical",
            "meditative",
            "traditional",
            "cinematic",
            "reflective",
        ],
        durationSeconds: 177,
        url: "https://media.seihouse.org/SEN/AUDIO/SOUNDSCAPE/Volumn%201/AMBIENT/10.%20AMBEINT.mp3",
    },
    {
        id: "SEN_VOL1_EMOTIONS_1",
        category: "Emotions",
        number: 1,
        title: "Melancholic String Lament",
        mood: "sad",
        tags: ["ambient", "sad", "tragedy", "mystical"],
        durationSeconds: 96,
        url: "https://media.seihouse.org/SEN/AUDIO/SOUNDSCAPE/Volumn%201/EMOTIONS/1.%20EMOTIONS.mp3",
    },
    {
        id: "SEN_VOL1_EMOTIONS_2",
        category: "Emotions",
        number: 2,
        title: "Ancient Lament",
        mood: "melancholic",
        tags: ["ambient", "mysterious", "ethnic", "soundscape"],
        durationSeconds: 177,
        url: "https://media.seihouse.org/SEN/AUDIO/SOUNDSCAPE/Volumn%201/EMOTIONS/2.%20EMOTIONS.mp3",
    },
    {
        id: "SEN_VOL1_EMOTIONS_3",
        category: "Emotions",
        number: 3,
        title: "Melancholic Wind Instrument Melody",
        mood: "sad",
        tags: ["ambient", "melancholic", "reflective", "cinematic", "emotional"],
        durationSeconds: 146,
        url: "https://media.seihouse.org/SEN/AUDIO/SOUNDSCAPE/Volumn%201/EMOTIONS/3.%20EMOTIONS.mp3",
    },
    {
        id: "SEN_VOL1_EMOTIONS_4",
        category: "Emotions",
        number: 4,
        title: "Mystic Woods Travel Theme",
        mood: "mystical",
        tags: ["adventure", "travel", "mystery", "mystical", "instrumental", "cinematic", "ethnic"],
        durationSeconds: 162,
        url: "https://media.seihouse.org/SEN/AUDIO/SOUNDSCAPE/Volumn%201/EMOTIONS/4.%20EMOTIONS.mp3",
    },
    {
        id: "SEN_VOL1_EMOTIONS_5",
        category: "Emotions",
        number: 5,
        title: "Melancholic Flute Soundscape",
        mood: "sad",
        tags: ["ambient", "historical", "cinematic", "melancholic", "meditative"],
        durationSeconds: 181,
        url: "https://media.seihouse.org/SEN/AUDIO/SOUNDSCAPE/Volumn%201/EMOTIONS/5.%20EMOTIONS.wav",
    },
    {
        id: "SEN_VOL1_EMOTIONS_6",
        category: "Emotions",
        number: 6,
        title: "Mystical Fanfare and Orchestral Ascent",
        mood: "mystical",
        tags: ["orchestral", "cinematic", "fantasy", "epic", "soundscape"],
        durationSeconds: 166,
        url: "https://media.seihouse.org/SEN/AUDIO/SOUNDSCAPE/Volumn%201/EMOTIONS/6.%20EMOTIONS.mp3",
    },
    {
        id: "SEN_VOL1_EMOTIONS_7",
        category: "Emotions",
        number: 7,
        title: "Melancholic Vocal Lament",
        mood: "sad",
        tags: ["ambient", "cinematic", "orchestral", "lament", "dramatic", "soundscape"],
        durationSeconds: 156,
        url: "https://media.seihouse.org/SEN/AUDIO/SOUNDSCAPE/Volumn%201/EMOTIONS/7.%20EMOTIONS.mp3",
    },
    {
        id: "SEN_VOL1_EMOTIONS_8",
        category: "Emotions",
        number: 8,
        title: "Traditional Winds and Strings Lament",
        mood: "sad",
        tags: ["ambient", "historical", "dramatic", "cinematic", "traditional"],
        durationSeconds: 159,
        url: "https://media.seihouse.org/SEN/AUDIO/SOUNDSCAPE/Volumn%201/EMOTIONS/8.%20ADVENTURE.mp3",
    },
    {
        id: "SEN_VOL1_EMOTIONS_9",
        category: "Emotions",
        number: 9,
        title: "Grand Orchestral Fanfare",
        mood: "triumph",
        tags: ["orchestral", "cinematic", "epic", "fantasy", "heroic", "soundscape", "dramatic"],
        durationSeconds: 160,
        url: "https://media.seihouse.org/SEN/AUDIO/SOUNDSCAPE/Volumn%201/EMOTIONS/9.%20EMOTIONS.mp3",
    },
    {
        id: "SEN_VOL1_EMOTIONS_10",
        category: "Emotions",
        number: 10,
        title: "Melancholic Flute and Cello Lament",
        mood: "sad",
        tags: ["ambient", "sad", "mystical", "tragedy", "serenity"],
        durationSeconds: 155,
        url: "https://media.seihouse.org/SEN/AUDIO/SOUNDSCAPE/Volumn%201/EMOTIONS/10.%20EMOTIONS.mp3",
    },
    {
        id: "SEN_VOL1_FIGHTING_1",
        category: "Fighting",
        number: 1,
        title: "Epic Tribal Drums and Brass Theme",
        mood: "epic",
        tags: ["cinematic", "orchestral", "percussive", "dramatic", "battle", "intense"],
        durationSeconds: 181,
        url: "https://media.seihouse.org/SEN/AUDIO/SOUNDSCAPE/Volumn%201/FIGHTING/1.%20Fighting.mp3",
    },
    {
        id: "SEN_VOL1_FIGHTING_2",
        category: "Fighting",
        number: 2,
        title: "Tribal Drums and Flute Soundscape",
        mood: "adventure",
        tags: [
            "adventure",
            "mystical",
            "ritual",
            "travel",
            "percussion",
            "cinematic",
            "soundscape",
        ],
        durationSeconds: 151,
        url: "https://media.seihouse.org/SEN/AUDIO/SOUNDSCAPE/Volumn%201/FIGHTING/2.%20Fighting.mp3",
    },
    {
        id: "SEN_VOL1_FIGHTING_3",
        category: "Fighting",
        number: 3,
        title: "Traditional Eastern Instrumental Ensemble",
        mood: "mystical",
        tags: ["adventure", "mystical", "travel", "tension", "traditional"],
        durationSeconds: 115,
        url: "https://media.seihouse.org/SEN/AUDIO/SOUNDSCAPE/Volumn%201/FIGHTING/3.%20Fighting.mp3",
    },
    {
        id: "SEN_VOL1_FIGHTING_4",
        category: "Fighting",
        number: 4,
        title: "Epic Tribal Battle Theme",
        mood: "fighting",
        tags: [
            "boss-fight",
            "war",
            "fighting",
            "adventure",
            "tension",
            "percussion",
            "cinematic",
            "choir",
        ],
        durationSeconds: 152,
        url: "https://media.seihouse.org/SEN/AUDIO/SOUNDSCAPE/Volumn%201/FIGHTING/4.%20Fighting.mp3",
    },
    {
        id: "SEN_VOL1_FIGHTING_5",
        category: "Fighting",
        number: 5,
        title: "Tribal Drums and Chants",
        mood: "triumph",
        tags: ["tribal", "ceremonial", "percussive", "rhythmic", "action", "epic"],
        durationSeconds: 154,
        url: "https://media.seihouse.org/SEN/AUDIO/SOUNDSCAPE/Volumn%201/FIGHTING/5.%20Fighting.mp3",
    },
    {
        id: "SEN_VOL1_FIGHTING_6",
        category: "Fighting",
        number: 6,
        title: "Tribal Drums of the Mystical Realm",
        mood: "tension",
        tags: ["percussive", "cinematic", "intense", "epic", "dark", "ritualistic", "action"],
        durationSeconds: 176,
        url: "https://media.seihouse.org/SEN/AUDIO/SOUNDSCAPE/Volumn%201/FIGHTING/6.%20Fighting.mp3",
    },
    {
        id: "SEN_VOL1_FIGHTING_7",
        category: "Fighting",
        number: 7,
        title: "Mystical Winds and Rhythmic Journey",
        mood: "mystical",
        tags: ["adventure", "mystical", "tension", "world-music", "cinematic", "rhythmic"],
        durationSeconds: 181,
        url: "https://media.seihouse.org/SEN/AUDIO/SOUNDSCAPE/Volumn%201/FIGHTING/7.%20Fighting.mp3",
    },
    {
        id: "SEN_VOL1_FIGHTING_8",
        category: "Fighting",
        number: 8,
        title: "Oriental Cinematic Epic Theme",
        mood: "epic",
        tags: ["epic", "cinematic", "percussive", "orchestral", "ethnic", "dramatic", "action"],
        durationSeconds: 177,
        url: "https://media.seihouse.org/SEN/AUDIO/SOUNDSCAPE/Volumn%201/FIGHTING/8.%20Fighting.mp3",
    },
    {
        id: "SEN_VOL1_FIGHTING_9",
        category: "Fighting",
        number: 9,
        title: "Traditional Eastern Fantasy Instrumental Theme",
        mood: "mystical",
        tags: [
            "cinematic",
            "percussive",
            "traditional",
            "epic",
            "dramatic",
            "rhythmic",
            "atmospheric",
        ],
        durationSeconds: 179,
        url: "https://media.seihouse.org/SEN/AUDIO/SOUNDSCAPE/Volumn%201/FIGHTING/9.%20Fighting.mp3",
    },
    {
        id: "SEN_VOL1_FIGHTING_10",
        category: "Fighting",
        number: 10,
        title: "Melancholic Wind Flute Soundscape",
        mood: "mystical",
        tags: ["ambient", "mystical", "cinematic", "traditional", "meditative"],
        durationSeconds: 156,
        url: "https://media.seihouse.org/SEN/AUDIO/SOUNDSCAPE/Volumn%201/FIGHTING/10.%20Fighting.mp3",
    },
    {
        id: "SEN_VOL1_WAR_1",
        category: "War",
        number: 1,
        title: "Tribal Drums and Chants in Ritual",
        mood: "epic",
        tags: ["percussion", "taiko", "chants", "tribal", "cinematic", "battle", "rhythmic"],
        durationSeconds: 172,
        url: "https://media.seihouse.org/SEN/AUDIO/SOUNDSCAPE/Volumn%201/WAR/1.%20WAR.wav",
    },
    {
        id: "SEN_VOL1_WAR_2",
        category: "War",
        number: 2,
        title: "Heavy Ritual Chant",
        mood: "dread",
        tags: ["fighting", "boss-fight", "tension", "dread", "heavy", "percussive", "choir"],
        durationSeconds: 147,
        url: "https://media.seihouse.org/SEN/AUDIO/SOUNDSCAPE/Volumn%201/WAR/2.%20WAR.mp3",
    },
    {
        id: "SEN_VOL1_WAR_3",
        category: "War",
        number: 3,
        title: "Epic Tribal Chants and Percussion",
        mood: "fighting",
        tags: ["percussion", "chants", "tribal", "battle", "dramatic", "aggressive", "epic"],
        durationSeconds: 60,
        url: "https://media.seihouse.org/SEN/AUDIO/SOUNDSCAPE/Volumn%201/WAR/3.%20WAR.mp3",
    },
]
